config/routes.rb
SCVSheriff::Application.routes.draw do

  resources :crimes

  resources :crime_tips do
    get :autocomplete_charge_name, :on => :collection
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :home, :only => [:index]

  resources :races

  resources :schools

  resources :drugs

  resources :students

  devise_for :users

  root :to => "welcome#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user

    if user.admin?
      can :manage, :all
    elsif user.has_role? :super_admin
      can :manage, [CrimeTip, Student]
    elsif user.has_role? :school_deputy
      can :manage, [Student]
    elsif user.has_role? :crime_tip_deputy
      can :manage, [CrimeTip]
    end
  end
end

app/models/assign.rb
class Assign < ActiveRecord::Base
  has_many :crime_tips
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/charge.rb
class Charge < ActiveRecord::Base
end

app/models/crime.rb
class Crime < ActiveRecord::Base

  has_many :crime_tips

end

app/models/crime_tip.rb
class CrimeTip < ActiveRecord::Base
  belongs_to :assign
  belongs_to :crime
  belongs_to :drug
  belongs_to :suspect_race, :class_name => "Race", :foreign_key => "suspect_race_id"
  belongs_to :suspect_school, :class_name => "School", :foreign_key => "suspect_school_id"
  belongs_to :zone

  has_many :tip_files

  accepts_nested_attributes_for :tip_files, :allow_destroy => true

  geocoded_by :location
  after_validation :geocode,:if => :street_number_changed? or :street_name_changed?

  acts_as_taggable_on :charges


  def suspect_name
    suspect_name = self.suspect_first_name + ' ' + self.suspect_last_name
  end

  def location
    [street_number, street_name, city, ].compact.join(' ')
  end

end

app/models/drug.rb
class Drug < ActiveRecord::Base

  has_many :students

end

app/models/race.rb
class Race < ActiveRecord::Base

  has_many :crime_tips
  has_many :students

end

app/models/risk_factor.rb
class RiskFactor < ActiveRecord::Base
  has_many :students
end

app/models/role.rb
class Role < ActiveRecord::Base
   has_many :assignments
   has_many :users, :through => :assignments
end

app/models/school.rb
class School < ActiveRecord::Base

  has_many :crime_tips
  has_many :students


end

app/models/student.rb
class Student < ActiveRecord::Base

  belongs_to :drug
  belongs_to :race
  belongs_to :school
  belongs_to :risk_factor
  belongs_to :updated_school, :class_name => "School", :foreign_key => "updated_school_id"
  belongs_to :deputy, :class_name => "User", :foreign_key => "school_deputy_id"

  if Rails.env  == 'development'
    has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" },
      :default_url => 'default_student.jpg'
  elsif Rails.env  == 'production'
      has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :default_url => 'default_student.jpg',
                    :storage => :s3,
                    :bucket => 'sheriff',
                    :s3_credentials => {:access_key_id => ENV['S3_KEY'], :secret_access_key => ENV['S3_SECRET']}
  end


  validates_presence_of :first_name

  def age(dob, now = Time.now.utc.to_date)
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

end

app/models/tip_file.rb
class TipFile < ActiveRecord::Base
  belongs_to :crime_tip

  if Rails.env  == 'development'
    has_attached_file :tip, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  elsif Rails.env  == 'production'
      has_attached_file :tip, :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :storage => :s3,
                    :bucket => 'sheriff',
                    :s3_credentials => {:access_key_id => ENV['S3_KEY'], :secret_access_key => ENV['S3_SECRET']}
  end

  #before_post_process :is_image?

  def is_image?
    ["image/jpeg", "image/pjpeg", "image/png", "image/x-png", "image/gif"].include?(@content_type)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable,:timeoutable, :registerable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :admin,:approved,:email, :password, :password_confirmation, :remember_me, :first_name, :last_name

  has_many :students, :class_name => "Student", :foreign_key => "school_deputy_id"

  has_many :assignments
  has_many :roles, :through => :assignments

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  def name
    if self.first_name.nil? and self.last_name.nil?
      name = ""
    else
      self.first_name + ' ' + self.last_name
    end
  end

  def has_role?(role_sym)
      roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end

  def school_deputy?
    has_role?(:school_deputy)
  end

end

app/models/zone.rb
class Zone < ActiveRecord::Base
  has_many :crime_tips
end

app/controllers/crime_tips_controller.rb
class CrimeTipsController < ApplicationController
  before_filter :authenticate_user!
  check_authorization
  load_and_authorize_resource
  autocomplete :charge, :name


  # GET /crime_tips
  # GET /crime_tips.json
  def index
    @search = CrimeTip.search(params[:search])
    @crime_tips = @search.paginate(:per_page => 25, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @crime_tips }
    end
  end

  # GET /crime_tips/1
  # GET /crime_tips/1.json
  def show
    @crime_tip = CrimeTip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @crime_tip }
    end
  end

  # GET /crime_tips/new
  # GET /crime_tips/new.json
  def new
    @crime_tip = CrimeTip.new

    1.times { @crime_tip.tip_files.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @crime_tip }
    end
  end

  # GET /crime_tips/1/edit
  def edit
    @crime_tip = CrimeTip.find(params[:id])
    1.times { @crime_tip.tip_files.build }
  end

  # POST /crime_tips
  # POST /crime_tips.json
  def create
    @crime_tip = CrimeTip.new(params[:crime_tip])

    respond_to do |format|
      if @crime_tip.save
        format.html { redirect_to @crime_tip, notice: 'Crime tip was successfully created.' }
        format.json { render json: @crime_tip, status: :created, location: @crime_tip }
      else
        format.html { render action: "new" }
        format.json { render json: @crime_tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /crime_tips/1
  # PUT /crime_tips/1.json
  def update
    @crime_tip = CrimeTip.find(params[:id])

    respond_to do |format|
      if @crime_tip.update_attributes(params[:crime_tip])
        format.html { redirect_to @crime_tip, notice: 'Crime tip was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @crime_tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crime_tips/1
  # DELETE /crime_tips/1.json
  def destroy
    @crime_tip = CrimeTip.find(params[:id])
    @crime_tip.destroy

    respond_to do |format|
      format.html { redirect_to crime_tips_url }
      format.json { head :ok }
    end
  end
end

app/helpers/crime_tips_helper.rb
module CrimeTipsHelper
end

app/helpers/crimes_helper.rb
module CrimesHelper
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/crime_tips/_form.html.haml
= form_for @crime_tip, :html => { :multipart => true } do |f|
  - if @crime_tip.errors.any?
    %div{:class => "alert-message block-message error"}
      %a.close{:href => "#"} &times;
      %p
        %strong
          = "#{pluralize(@crime_tip.errors.count, "error")} prohibited this student from being saved:"
        %ul
          - @crime_tip.errors.full_messages.each do |msg|
            %li= msg

  .fieldset
    .legend
    .clearfix
      = f.label :date_rec
      .input
        = f.text_field :date_rec
    .clearfix
      = f.label :date_due
      .input
        = f.text_field :date_due
    .clearfix
      = f.label :crime_id
      .input
        = select(:crime_tip, :crime_id, Crime.all.collect {|p| [p.name, p.id]}, {:include_blank => true})
    .clearfix
      = f.label :street_number
      .input
        = f.text_field :street_number
    .clearfix
      = f.label :street_name
      .input
        = f.text_field :street_name
    .clearfix
      = f.label :cross_street
      .input
        = f.text_field :cross_street
    .clearfix
      = f.label :city
      .input
        = f.text_field :city
    .clearfix
      = f.label :zone
      .input
        = select(:crime_tip, :zone_id, Zone.all.collect {|p| [p.name, p.id]}, {:include_blank => true})
    .clearfix
      = f.label :informant_name
      .input
        = f.text_field :informant_name
    .clearfix
      = f.label :informant_phone
      .input
        = f.text_field :informant_phone
    .clearfix
      = f.label :informant_email
      .input
        = f.text_field :informant_email
    .clearfix
      = f.label :suspect_first_name
      .input
        = f.text_field :suspect_first_name
    .clearfix
      = f.label :suspect_last_name
      .input
        = f.text_field :suspect_last_name
    .clearfix
      = f.label :suspect_dob
      .input
        = f.date_select :suspect_dob,
          :start_year => Time.now.year - 75,
          :end_year => Time.now.year,
          :include_blank  => 'true'
    .clearfix
      = f.label :suspect_age
      .input
        = f.text_field :suspect_age
    .clearfix
      = f.label :suspect_race_id
      .input
        = select(:crime_tip, :suspect_race_id, Race.all.collect {|p| [p.name,p.id]})
    .clearfix
      = f.label :suspect_gender
      .input
        = select(:crime_tip, :suspect_gender, options_for_select([['',''],['M', 'M'],['F', 'F']]))
    .clearfix
      = f.label :suspect_street_number
      .input
        = f.text_field :suspect_street_number
    .clearfix
      = f.label :suspect_street_name
      .input
        = f.text_field :suspect_street_name
    .clearfix
      = f.label :suspect_city
      .input
        = f.text_field :suspect_city
    .clearfix
      = f.label :suspect_school_id
      .input
        = select(:crime_tip, :suspect_school_id, School.all.collect {|p| [p.name, p.id]}, {:include_blank => true})
    .clearfix
      = f.label :suspect_phone
      .input
        = f.text_field :suspect_phone
    .clearfix
      = f.label :suspect_cell
      .input
        = f.text_field :suspect_cell
    .clearfix
      = f.label :suspect_2
      .input
        = f.text_field :suspect_2
    .clearfix
      = f.label :suspect_3
      .input
        = f.text_field :suspect_3
    .clearfix
      = f.label :gang
      .input
        = f.text_field :gang
    .clearfix
      = f.label :vehicle
      .input
        = f.text_field :vehicle
    .clearfix
      = f.label :license_plate
      .input
        = f.text_field :license_plate
    .clearfix
      = f.label :drug_id
      .input
        = select(:crime_tip, :drug_id, Drug.all.collect {|p| [p.name, p.id]}, {:include_blank => true})
    .clearfix
      = f.label :assign_id
      .input
        = select(:crime_tip, :assign_id, Assign.all.collect {|p| [p.team, p.id]}, {:include_blank => true})
    .clearfix
      = f.label :date_assigned
      .input
        = f.text_field :date_assigned
    .clearfix
      = f.label :date_completed
      .input
        = f.text_field :date_completed
    .clearfix
      = f.label :charges
      .input
        = f.autocomplete_field :charge_list, autocomplete_charge_name_crime_tips_path, :"data-delimiter" => ', '
    .clearfix
      = f.label :urn
      .input
        = f.text_field :urn
    .clearfix
      = f.label :clearance
      .input
        = f.text_area :clearance, {:rows => "5", :class => "xxlarge"}
    .clearfix
      = f.label :side_notes
      .input
        = f.text_area :side_notes, {:rows => "5", :class => "xxlarge"}
    .clearfix
      = f.label :search_warrant
      .input
        = f.check_box :search_warrant
    .clearfix
      = f.label :probation_search
      .input
        = f.check_box :probation_search
    .clearfix
      = f.label :parole_search
      .input
        = f.check_box :parole_search
    .clearfix
      = f.label :arrested
      .input
        = f.check_box :arrested
    .clearfix
      = f.label :status
      .input
        = select(:crime_tip, :status, options_for_select([['Open', 'Open'],['Closed', 'Closed']]))
    .clearfix
      = f.fields_for :tip_files do |file_fields|
        &nbsp;
        - if file_fields.object.new_record?
          .input
            = file_fields.file_field :tip
    .clearfix
      = f.fields_for :tip_files do |file_fields|
        - unless file_fields.object.new_record?
          .input
            = link_to file_fields.object.tip_file_name, file_fields.object.tip.url(:original)
            &nbsp;
            = file_fields.check_box :_destroy
            Remove
    .actions
      = f.submit 'Save', {:class => "btn primary"}

app/views/crime_tips/edit.html.haml
%h1 Editing Crime Tip

= render 'form'

= link_to 'Show', @crime_tip
\|
= link_to 'Back', crime_tips_path

app/views/crime_tips/index.html.haml
%h1 Crime Tips

= form_for @search do |f|
  .well
    .row
      .span7
        .clearfix
          = f.label :tip_number_contains, 'Tip Number'
          .input
            = f.text_field :tip_number_contains
        .clearfix
          = f.label :crime_name_contains, 'Crime Type'
          .input
            = f.collection_select :crime_name_contains, Crime.all, :name, :name, :include_blank => true
        .clearfix
          = f.label :date_rec, 'Date Received'
          .input
            = f.text_field :date_rec_gte
        .clearfix
          = f.label :street_number_contains,'Street Number'
          .input
            = f.text_field :street_number_contains
        .clearfix
          = f.label :street_name_contains, 'Street Name'
          .input
            = f.text_field :street_name_contains
        .clearfix
          = f.label 'City'
          .input
            = f.text_field :city_contains

      .span5
        .clearfix
          = f.label :informant_name_contains, 'Informant Name'
          .input
            = f.text_field :informant_name_contains
        .clearfix
          = f.label :suspect_first_name_contains, 'Suspect First Name'
          .input
            = f.text_field :suspect_first_name_contains
        .clearfix
          = f.label :suspect_last_name_contains, 'Suspect Last Name'
          .input
            = f.text_field :suspect_last_name_contains
        .clearfix
          = f.label :assign_team_contains, 'Assigned'
          .input
            = f.collection_select :assign_team_contains, Assign.all, :team, :team, :include_blank => true
        .clearfix
          = f.label :status_contains, 'Status'
          .input
            = f.select(:status_contains, options_for_select([['Open', 'Open'],['Closed', 'Closed']]), :include_blank => true )
        .clearfix
          = f.label :zone_name_contains, 'Zone'
          .input
            = f.collection_select :zone_name_contains, Zone.all, :name, :name, :include_blank => true

    = submit_tag 'Search',:name => nil, :class => "btn primary"


%table#CrimeTipsTable.zebra-striped
  %thead
    %tr
      %th Tip Number
      %th Date Received
      %th Crime
      %th Location
      %th Zone
      %th Suspect Name
      %th Assigned
      %th
      %th
      %th

  - @crime_tips.each do |crime_tip|
    %tr
      %td= crime_tip.tip_number
      %td= crime_tip.date_rec.strftime("%m/%d/%Y") unless crime_tip.date_rec.nil?
      %td= crime_tip.crime.name unless crime_tip.crime.nil?
      %td= crime_tip.street_number + ' '+  crime_tip.street_name
      %td= crime_tip.zone.name unless crime_tip.zone.nil?
      %td= crime_tip.suspect_name.upcase
      %td= crime_tip.assign.team unless crime_tip.assign.nil?
      %td= link_to 'Show', crime_tip
      %td= link_to 'Edit', edit_crime_tip_path(crime_tip)
      %td= link_to 'Destroy', crime_tip, :confirm => 'Are you sure?', :method => :delete

= will_paginate @crime_tips
%br

= link_to 'New Crime Tip', new_crime_tip_path, :class => 'btn primary'

app/views/crime_tips/new.html.haml
%h1 New Crime Tip

= render 'form'

= link_to 'Back', crime_tips_path

app/views/crime_tips/show.html.haml
%h2
  Tip Number
  = @crime_tip.tip_number

%br
%ul.tabs{"data-tabs" => "tabs"}
  %li.active
    %a{:href => "#home"} Home
  %li
    %a{:href => "#location"} Location
  %li
    %a{:href => "#informant"} Informant
  %li
    %a{:href => "#suspect"} Suspect
  %li
    %a{:href => "#files"} Files

#my-tab-content.tab-content
  #home.active
    %p
      %b Date rec:
      = @crime_tip.date_rec.strftime("%m/%d/%Y") unless @crime_tip.date_rec.nil?
    %p
      %b Date due:
      = @crime_tip.date_due.strftime("%m/%d/%Y") unless @crime_tip.date_due.nil?
    %p
      %b Crime:
      = @crime_tip.crime.name unless @crime_tip.crime.nil?
    %p
      %b Assigned:
      = @crime_tip.assign.team unless @crime_tip.assign.nil?
    %p
      %b Date assigned:
      = @crime_tip.date_assigned.strftime("%m/%d/%Y") unless @crime_tip.date_assigned.nil?
    %p
      %b Date completed:
      = @crime_tip.date_completed.strftime("%m/%d/%Y") unless @crime_tip.date_completed.nil?
    %p
      %b Charges:
      = @crime_tip.charge_list
    %p
      %b Urn:
      = @crime_tip.urn
    %p
      %b Clearance:
      = @crime_tip.clearance
    %p
      %b Side notes:
      = @crime_tip.side_notes
    %p
      %b Search warrant:
      = @crime_tip.search_warrant ? 'Yes' : 'No'
    %p
      %b Probation search:
      = @crime_tip.probation_search ? 'Yes' : 'No'
    %p
      %b Parole search:
      = @crime_tip.parole_search ? 'Yes' : 'No'
    %p
      %b Arrested:
      = @crime_tip.arrested ? 'Yes' : 'No'
    %p
      %b Status:
      = @crime_tip.status
  #location
    %p
      %b Street number:
      = @crime_tip.street_number
    %p
      %b Street name:
      = @crime_tip.street_name
    %p
      %b Cross street:
      = @crime_tip.cross_street
    %p
      %b City:
      = @crime_tip.city
    - unless @crime_tip.latitude.nil? || @crime_tip.longitude.nil?
      = image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@crime_tip.latitude}%2C#{@crime_tip.longitude}"
    %p
      %b Zone:
      = @crime_tip.zone.name unless @crime_tip.zone.nil?
  #informant
    %p
      %b Informant name:
      = @crime_tip.informant_name
    %p
      %b Informant phone:
      = @crime_tip.informant_phone
    %p
      %b Informant email:
      = @crime_tip.informant_email
  #suspect
    %p
      %b Suspect first name:
      = @crime_tip.suspect_first_name.upcase
    %p
      %b Suspect last name:
      = @crime_tip.suspect_last_name.upcase
    %p
      %b Suspect dob:
      = @crime_tip.suspect_dob.strftime("%m/%d/%Y") unless @crime_tip.suspect_dob.nil?
    %p
      %b Suspect age:
      = @crime_tip.suspect_age
    %p
      %b Suspect race:
      = @crime_tip.suspect_race.name unless @crime_tip.suspect_race.nil?
    %p
      %b Suspect gender:
      = @crime_tip.suspect_gender
    %p
      %b Suspect street number:
      = @crime_tip.suspect_street_number
    %p
      %b Suspect street name:
      = @crime_tip.suspect_street_name
    %p
      %b Suspect city:
      = @crime_tip.suspect_city
    %p
      %b Suspect school:
      = @crime_tip.suspect_school.name unless @crime_tip.suspect_school.nil?
    %p
      %b Suspect phone:
      = @crime_tip.suspect_phone
    %p
      %b Suspect cell:
      = @crime_tip.suspect_cell
    %p
      %b Gang:
      = @crime_tip.gang
    %p
      %b Vehicle:
      = @crime_tip.vehicle
    %p
      %b License plate:
      = @crime_tip.license_plate
    %p
      %b Drug:
      = @crime_tip.drug.name unless @crime_tip.drug.nil?
    %p
      %b Suspect 2:
      = @crime_tip.suspect_2
    %p
      %b Suspect 3:
      = @crime_tip.suspect_3
  #files
    - @crime_tip.tip_files.each do |tip_files|
      %p
        = image_tag tip_files.tip.url(:thumb)
        %br
        = link_to tip_files.tip_file_name, tip_files.tip.url(:original), :target => "_blank"

%br
%br

= link_to 'Edit', edit_crime_tip_path(@crime_tip), :class => 'btn primary'
&nbsp;
= link_to 'Back', crime_tips_path, :class => 'btn'