config/routes.rb
SCVSheriff::Application.routes.draw do

  resources :crimes

  resources :crime_tips do
    get :autocomplete_charge_name, :on => :collection
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :home, :only => [:index]

  resources :races

  resources :schools

  resources :drugs

  resources :students

  devise_for :users

  root :to => "welcome#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user

    if user.admin?
      can :manage, :all
    elsif user.has_role? :super_admin
      can :manage, [CrimeTip, Student]
    elsif user.has_role? :school_deputy
      can :manage, [Student]
    elsif user.has_role? :crime_tip_deputy
      can :manage, [CrimeTip]
    end
  end
end

app/models/assign.rb
class Assign < ActiveRecord::Base
  has_many :crime_tips
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/charge.rb
class Charge < ActiveRecord::Base
end

app/models/crime.rb
class Crime < ActiveRecord::Base

  has_many :crime_tips

end

app/models/crime_tip.rb
class CrimeTip < ActiveRecord::Base
  belongs_to :assign
  belongs_to :crime
  belongs_to :drug
  belongs_to :suspect_race, :class_name => "Race", :foreign_key => "suspect_race_id"
  belongs_to :suspect_school, :class_name => "School", :foreign_key => "suspect_school_id"
  belongs_to :zone

  has_many :tip_files

  accepts_nested_attributes_for :tip_files, :allow_destroy => true

  geocoded_by :location
  after_validation :geocode,:if => :street_number_changed? or :street_name_changed?

  acts_as_taggable_on :charges


  def suspect_name
    suspect_name = self.suspect_first_name + ' ' + self.suspect_last_name
  end

  def location
    [street_number, street_name, city, ].compact.join(' ')
  end

end

app/models/drug.rb
class Drug < ActiveRecord::Base

  has_many :students

end

app/models/race.rb
class Race < ActiveRecord::Base

  has_many :crime_tips
  has_many :students

end

app/models/risk_factor.rb
class RiskFactor < ActiveRecord::Base
  has_many :students
end

app/models/role.rb
class Role < ActiveRecord::Base
   has_many :assignments
   has_many :users, :through => :assignments
end

app/models/school.rb
class School < ActiveRecord::Base

  has_many :crime_tips
  has_many :students


end

app/models/student.rb
class Student < ActiveRecord::Base

  belongs_to :drug
  belongs_to :race
  belongs_to :school
  belongs_to :risk_factor
  belongs_to :updated_school, :class_name => "School", :foreign_key => "updated_school_id"
  belongs_to :deputy, :class_name => "User", :foreign_key => "school_deputy_id"

  if Rails.env  == 'development'
    has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" },
      :default_url => 'default_student.jpg'
  elsif Rails.env  == 'production'
      has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :default_url => 'default_student.jpg',
                    :storage => :s3,
                    :bucket => 'sheriff',
                    :s3_credentials => {:access_key_id => ENV['S3_KEY'], :secret_access_key => ENV['S3_SECRET']}
  end


  validates_presence_of :first_name

  def age(dob, now = Time.now.utc.to_date)
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

end

app/models/tip_file.rb
class TipFile < ActiveRecord::Base
  belongs_to :crime_tip

  if Rails.env  == 'development'
    has_attached_file :tip, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  elsif Rails.env  == 'production'
      has_attached_file :tip, :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :storage => :s3,
                    :bucket => 'sheriff',
                    :s3_credentials => {:access_key_id => ENV['S3_KEY'], :secret_access_key => ENV['S3_SECRET']}
  end

  #before_post_process :is_image?

  def is_image?
    ["image/jpeg", "image/pjpeg", "image/png", "image/x-png", "image/gif"].include?(@content_type)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable,:timeoutable, :registerable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :admin,:approved,:email, :password, :password_confirmation, :remember_me, :first_name, :last_name

  has_many :students, :class_name => "Student", :foreign_key => "school_deputy_id"

  has_many :assignments
  has_many :roles, :through => :assignments

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  def name
    if self.first_name.nil? and self.last_name.nil?
      name = ""
    else
      self.first_name + ' ' + self.last_name
    end
  end

  def has_role?(role_sym)
      roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end

  def school_deputy?
    has_role?(:school_deputy)
  end

end

app/models/zone.rb
class Zone < ActiveRecord::Base
  has_many :crime_tips
end

app/helpers/crimes_helper.rb
module CrimesHelper
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/_nav.html.haml
.topbar-wrapper{:style => "z-index: 5;"}
  .topbar{"data-dropdown" => "dropdown"}
    .topbar-inner
      .container
        %h3
          = link_to 'SCV Sheriff', root_path
        - if user_signed_in?
          %ul.nav
            %li
              = active_link_to 'Home', home_index_path, :wrap_tag => :li
            %li
              = active_link_to 'Students', students_path, :wrap_tag => :li
            %li
              = active_link_to 'Crime Tips', crime_tips_path, :wrap_tag => :li
            %ul{:class => "nav secondary-nav"}
              %li.dropdown
                = link_to 'User', '#', {:class => 'dropdown-toggle'}
                %ul.dropdown-menu
                  %li
                    = link_to 'Account Settings', edit_user_registration_path
                  %li.divider
                  %li
                    = link_to('Logout', destroy_user_session_path, :method => :delete)
          - else
            %ul.nav
              %li
                = link_to 'Sign In', home_index_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title SCVSheriff
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body{:style => 'padding-top: 40px;'}
    = render 'layouts/nav'
    .container-fluid
      .sidebar
      .content{:style => 'padding-top: 10px'}
        - if flash[:notice]
          .div{:class => 'alert-message success fade in', 'data-alert' => 'alert'}
            %a.close{:href => '#'} x
            %p
              %strong
                = notice
        - if flash[:alert]
          .div{:class => 'alert-message info fade in', 'data-alert' => 'alert'}
            %a.close{:href => '#'} x
            %p
              %strong
                = alert

        = yield

    %footer.footer
      .container
        %p.pull-right
          %a{:href => "#"} Back to top
        %p
          = image_tag 'city_seal_footer.png'
          = image_tag 'LASD_Logo.gif'
        %p
        ©2011 Los Angeles County Sheriff and the City of Santa Clarita.